### ISSUE TITLE
Backward-incompatible change released as minor version

### ISSUE THREAD

**Issue by christianbundy** [dachev/node-cld#56]
See also: https://github.com/dachev/node-cld/issues/55

I'm a bit confused and looking for some clarity as to why the backward-incompatible version change was introduced as a minor version bump. I read through the other issue but I'm not clear on why it was closed.

> Major version X (X.y.z | X > 0) MUST be incremented if any backwards incompatible changes are introduced to the public API. It MAY include minor and patch level changes. Patch and minor version MUST be reset to 0 when major version is incremented.

Is the current stance that dependency changes that require manual intervention are understood to be "backward compatible"? This broke the build for me and seems like a breaking change.

Thanks for your help!

---

Just some notes: this sort of issue is often called the [diamond dependency problem](https://www.well-typed.com/blog/2008/04/the-dreaded-diamond-dependency-problem/) and when [it comes up in the semver repo](https://github.com/semver/semver/issues?utf8=%E2%9C%93&q=diamond) the recommendation always seems to be "release breaking changes as a major version to avoid breaking builds".

There may be some context about node-cld that I'm missing, but I'd love to unbreak the build without having to only trust patch version bumps.

**Comment by dachev** [comment]
@chaosgame I elected to bump the minor version number precisely because of the semver rules as I made no changes to the public API.

I decided to address build incompatibility by declaring node engine support in package.json which is supposed to allow to `...specify the version of node that your stuff works on:`. I naively thought that npm will select the latest compatible release when picking a version.

As it turns out this field doesn't do anything and is pretty much ignored by npm. Also buried at the end of the documentation is this gem: `Unless the user has set the engine-strict config flag, this field is advisory only and will only produce warnings when your package is installed as a dependency.`

`engine-strict` has been removed long time ago.

**Comment by dachev** [comment]
It boils down to npm false advertising features that lead up to a problem that I don't have time to deal with anymore.

**Comment by dachev** [comment]
FWIW this has nothing to do with the diamond dependency problem. It's a problem created by our inability to target node version availability yet depend on node engine features to compile.

**Comment by christianbundy** [comment]
Is there anything that I can do to help?

**Comment by dachev** [comment]
I can try to find some time on the weekend and see what I can do to minimize the impact but it may be faster to just pin your dependency to 2.4.8
